"""add_max_runs_to_schedule

Revision ID: 28b6635e5adc
Revises: a3f1c8d92e47
Create Date: 2026-03-28 12:03:28.314034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28b6635e5adc"
down_revision: Union[str, Sequence[str], None] = "a3f1c8d92e47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # max_runs was already added in a partial run; only add run_count
    try:
        op.add_column("asset_schedules", sa.Column("max_runs", sa.Integer(), nullable=True))
    except Exception:  # noqa: BLE001
        pass  # Column already exists from partial migration
    op.add_column(
        "asset_schedules", sa.Column("run_count", sa.Integer(), nullable=False, server_default="0")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("asset_schedules", "run_count")
    op.drop_column("asset_schedules", "max_runs")
    # ### end Alembic commands ###
