"""initial_schema

Revision ID: d9c999ae717a
Revises:
Create Date: 2026-02-17 19:32:03.888449

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d9c999ae717a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("tax_id", sa.String(length=13), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("marital_status", sa.String(length=20), nullable=False),
        sa.Column("number_of_children", sa.Integer(), nullable=False),
        sa.Column("number_of_parents", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tax_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "deductions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("deduction_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("maximum_allowed", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("document_reference", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deductions_tax_year"), "deductions", ["tax_year"], unique=False)
    op.create_index(op.f("ix_deductions_user_id"), "deductions", ["user_id"], unique=False)
    op.create_table(
        "financial_goals",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("goal_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("current_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_goals_user_id"), "financial_goals", ["user_id"], unique=False
    )
    op.create_table(
        "incomes",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("income_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("pay_period", sa.String(length=20), nullable=False),
        sa.Column("employer_name", sa.String(length=255), nullable=True),
        sa.Column("withholding_tax", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incomes_tax_year"), "incomes", ["tax_year"], unique=False)
    op.create_index(op.f("ix_incomes_user_id"), "incomes", ["user_id"], unique=False)
    op.create_table(
        "investment_holdings",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("average_cost_per_unit", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("current_price_per_unit", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("current_value", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("unrealized_gain_loss", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("last_price_update", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_investment_holdings_user_id"), "investment_holdings", ["user_id"], unique=False
    )
    op.create_table(
        "tax_filings",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("tax_year", sa.Integer(), nullable=False),
        sa.Column("gross_income", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_deductions", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("net_income", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_tax", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("effective_tax_rate", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("withholding_tax_paid", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_due_or_refund", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("filing_status", sa.String(length=20), nullable=False),
        sa.Column("tax_breakdown_json", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tax_year", name="uq_user_tax_year"),
    )
    op.create_index(op.f("ix_tax_filings_user_id"), "tax_filings", ["user_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("holding_id", sa.String(length=36), nullable=True),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("price_per_unit", sa.Numeric(precision=16, scale=4), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("reference_number", sa.String(length=100), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["holding_id"],
            ["investment_holdings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_holding_id"), "transactions", ["holding_id"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_transaction_date"), "transactions", ["transaction_date"], unique=False
    )
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_transaction_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_holding_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_tax_filings_user_id"), table_name="tax_filings")
    op.drop_table("tax_filings")
    op.drop_index(op.f("ix_investment_holdings_user_id"), table_name="investment_holdings")
    op.drop_table("investment_holdings")
    op.drop_index(op.f("ix_incomes_user_id"), table_name="incomes")
    op.drop_index(op.f("ix_incomes_tax_year"), table_name="incomes")
    op.drop_table("incomes")
    op.drop_index(op.f("ix_financial_goals_user_id"), table_name="financial_goals")
    op.drop_table("financial_goals")
    op.drop_index(op.f("ix_deductions_user_id"), table_name="deductions")
    op.drop_index(op.f("ix_deductions_tax_year"), table_name="deductions")
    op.drop_table("deductions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
